### ISSUE TITLE
toast 出现之后,在它消失之前,禁止点击其他区域怎么改呢

### ISSUE THREAD

**Issue by lcyh** [clancysong/react-components#1]
我的是 submit提交,如果有 input框没有输入或者输入格式不对,submit提交时会出现 toast,但是toast消失之前想让这个时间段内不能点击input框focus(toast消失之前改页面要屏蔽掉任何点击事件,知道toast消失之后才能恢复点击),等toast消失之后才能点击(这里是移动端的 表单提交)

**Comment by clancysong** [comment]
很抱歉没能及时回复，大概早已经找到合适的解决方案了吧，十分抱歉。

**Comment by lcyh** [comment]
可以给 toast组件的外层加个透明浮层覆盖整屏,达到禁止点击效果




------------------ 原始邮件 ------------------
发件人: "clancysong"<notifications@github.com>; 
发送时间: 2019年8月1日(星期四) 下午3:21
收件人: "clancysong/react-components"<react-components@noreply.github.com>; 
抄送: "不同的选择"<173408798@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [clancysong/react-components] toast 出现之后,在它消失之前,禁止点击其他区域怎么改呢 (#1)




Closed #1.

**Comment by lcyh** [comment]
解决了
