### ISSUE TITLE
生命周期函数里面不起作用

### ISSUE THREAD

**Issue by TinkerDeng** [clancysong/react-components#2]
componentDidMount(){
Toast.info();
}

//error：cannot read property addNotice of null 
生命周期里面ReactDOM.render 对象返回的是null

**Comment by clancysong** [comment]
十分抱歉没能及时解答您的问题，根据反馈新版本的 React 中 ReactDOM.render 返回值为空（测试 React 16.4 版本正常），我会在后续重构这部分代码，抱歉给您带来了困扰。

**Comment by clancysong** [comment]
十分抱歉没能及时回复。
谢谢你的反馈，我会在后续修复这部分代码，抱歉给你带来了困扰。
