### ISSUE TITLE
一个很小的代码书写疑问

### ISSUE THREAD

**Issue by AlanWenhao** [clancysong/react-components#3]
### 很小的一个疑问
在`toast.js`中：
https://github.com/clancysong/react-components/blob/master/components/toast/toast.js#L12
https://github.com/clancysong/react-components/blob/master/components/toast/toast.js#L24
https://github.com/clancysong/react-components/blob/master/components/toast/toast.js#L29
#### 这里不用 `return` 代码也是同样的运行逻辑吧
因为我书写代码的习惯这里不会写`return`的
想确认的是：在这里函数中这么使用 `return` 是由他存在的意义吗？还是作者也只是习惯

**Comment by cicec** [comment]
十分抱歉现在才看到你的问题。
这里使用 return 是为了返回一个移除自身的函数给调用者以便根据需要立即移除这条提示。这个函数在 notification.js 的 addNotice 函数中被声明。
希望能够解决你的疑问。

**Comment by AlanWenhao** [comment]
嗯，感谢回答，其实我的问题事项确实一个写法的意义，比如这些逻辑给我写，`toast.js` 的28~30行，我会这么写：
```
info(content, duration, onClose) {
        notice('info', content, duration, onClose)
},
```
你的写法是：
```
info(content, duration, onClose) {
       return notice('info', content, duration, onClose)
},
```
差别：仅仅多了一个 `return`，这个问题其实比较钻牛角尖，见谅哈~，我想确认的是：这里不写 `return`，代码可以正常运行，不知道这样会不会对逻辑造成影响。
提问初衷：
因为我写代码平时不会这样return，学习你代码的时候看到这么写，不能保证这里是否有他的意义所在

**Comment by cicec** [comment]
我明白你的意思，因为这里需要将这个移除自身的函数返回给调用者，如果不写 return 的话，这个函数是没有返回值的，移除自身的函数也就没办法传递出去。

例如这段代码，如果组件中不写 return 的话，那么这个 hideLoading 函数是无法生效的，组件会一直显示在页面中：

```` js
const hideLoading = Toast.loading('加载中...', 0, () => {
    Toast.success('加载成功')
})
setTimeout(hideLoading, 2000)
````

**Comment by AlanWenhao** [comment]
了解，很感谢你的回答😁
